### ISSUE TITLE
ERROR_INSTALL_NOT_ALLOWED

### ISSUE THREAD

**Issue by SandaBurido** [feilfeilundfeil/flutter_in_app_update#24]
I'm get this error when run checkForUpdate():
PlatformException (PlatformException(Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED), null, null))

How can i fix it. Sr i'm newbie.

**Comment by jonasbark** [comment]
Look into the documentation. The error clearly states what might go wrong.

**Comment by tehsunnliu** [comment]
Hi, I'm getting the same error. And the error only states `The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...)`
I'm running on the emulator with a full battery and more than 4G disk space and still getting this error.
Is it some permission issue?

**Comment by tehsunnliu** [comment]
Okay, the reason was that I wasn't logged in to the google play store.
